[package]
name = "aoc2018"
version = "0.1.0"
edition = "2021"
authors= [ "Pieter Bruyninckx"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
ndarray = "0.15.6"
